apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: notes-app
data:
  # This matches the name of the Redis service we are about to create
  REDIS_HOST: "redis-service" 
  AUTH_SERVICE_URL: "http://auth-service:8000"